# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuPlease.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 130, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(520, 140, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 801, 581))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../Desktop/Extra stuff/design flash/nasheed time/clouds_aerial_photography-wallpaper-1366x768.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(270, 310, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.display.setFont(font)
        self.display.setAlignment(QtCore.Qt.AlignCenter)
        self.display.setObjectName("display")
        self.order = QtWidgets.QPushButton(self.centralwidget)
        self.order.setGeometry(QtCore.QRect(290, 440, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.order.setFont(font)
        self.order.setObjectName("order")
        self.label_2.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label.raise_()
        self.display.raise_()
        self.order.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Adding items to combo box aka dropdown menu
        #self.comboBox.addItem("Chicken")
        
        # Setting index of the item in the comboBox
        #index = self.comboBox.findText("Chicken", QtCore.Qt.MatchFixedString)
        #self.comboBox.setCurrentIndex(index)
        
        self.order.clicked.connect(self.despo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Soup"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Sandwiches"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Rice"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Steak"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Coke"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Mineral Water"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Cocktail"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Tea"))
        self.label.setText(_translate("MainWindow", "Menu"))
        self.display.setText(_translate("MainWindow", ""))
        self.order.setText(_translate("MainWindow", "Order Now!"))
        
    def despo(self):
        print(self.comboBox.currentText())
        print(self.comboBox_2.currentText())
        self.display.setText(f"You've chosen {self.comboBox.currentText()} and {self.comboBox_2.currentText()}.")
        self.display.adjustSize()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
